### ISSUE TITLE
BUG: Always double jump when keybind is set to spacebar

### ISSUE THREAD

**Issue by Turioyt** [dangbroitsdon/Wall-Jump-Unofficial-Fabric#1]
I found a possible bug.
When double jump is enabled and the keybind is set to spacebar you always double jump (jump twice). You waste both jumps by just pressing to spacebar once. I'm not sure if this is intentional or not but I'd personally rather be able to single jump then jump again while mid-air instead of both at the same time.

Steps to reproduce:
-Enable double jumping
-Set double jump keybind set to spacebar
-Jump

**Comment by dangbroitsdon** [comment]
How did it even work? It should conflict with normal Jump, or at least for me it has.

**Comment by dangbroitsdon** [comment]
Nevertheless, in the new build there is a config option for it now, if you want to enable the classic double jump which is using Spacebar.
