### ISSUE TITLE
The mod is incompatible with Hardcore Revival

### ISSUE THREAD

**Issue by BLUEChester** [dangbroitsdon/Wall-Jump-Unofficial-Fabric#5]
When dieing with the Hardcore Revival mod the 'falling sound' repeatedly plays, extremely loud. Setting the 'playFallSound' to false didn't work either, I set it to false both on the client and the server, but it still played.

The Hardcore Revival mod developer said that their mod doesn't add any sounds, so it must be this mod.

This is on a fabric server in 1.19

**Comment by dangbroitsdon** [comment]
sorry for the SUUUUUUPER LATE response but ill look into it

**Comment by dangbroitsdon** [comment]
FIXED NOW BABY!!!!!!

**Comment by BLUEChester** [comment]
Wow! No that's totally a fast response thank you so much didn't expect to even get a response, especially this quick. Thank you so much man I really really appreciate this! We really didn't want to remove this mod because it makes movement and adventuring in our modpack so much more satisfying and fun!

Have a brilliant week dude!

**Comment by dangbroitsdon** [comment]
no problem man, and you have a great week too!
