### ISSUE TITLE
Idea: Add exhaustion effect

### ISSUE THREAD

**Issue by mrniddala** [dangbroitsdon/Wall-Jump-Unofficial-Fabric#7]
Hello, I was playing now the last days with the mod on my server, super well 🥰
I would love to setup exhaustion effect for climbing and double jump, to balance it more.
Greetings 😊

**Comment by dangbroitsdon** [comment]
perhaps.

**Comment by mrniddala** [comment]
Hello @dangbroitsdon, I found out that you can stop the Levitation effect while you climbing at a wall.
Is this intended? Add maybe a config option for that 😋

**Comment by dangbroitsdon** [comment]
could not reproduce the stopping of the levitation effect and adding a config option didn't work for it, but in the next update the exhaustion will be implemented, it was partially implemented with wall jumps but not actual double jumps

**Comment by mrniddala** [comment]
Awesome, thanks a lot - makes everything more vanillish 🥰

**Comment by dangbroitsdon** [comment]
no problemo
