### ISSUE TITLE
[1.18, 1.19] Slow flying in creative mode and spectator mode

### ISSUE THREAD

**Issue by artemisSystem** [dangbroitsdon/Wall-Jump-Unofficial-Fabric#9]
I noticed that:
- After doing a wall jump in creative mode, your flight speed slows down to be about the pace of walking indefinitely
- In spectator mode, scrolling only affects your movement speed *while* you are scrolling, it seems speed is related to how much you are scrolling during that frame or something. If you stop scrolling, you go back to normal speed.

If i comment out the `miscellaneousTickMovement` mixin in `ClientPlayerEntitySpeedBoostMixin`, these issues do not occur, so i assume there are some wrong assumptions being made in the `SpeedBoostLogic.doSpeedBoost()` method. This does not occur in the forge 1.18.2 version of wall jump.

**Comment by artemisSystem** [comment]
After more research, i've found commenting out this line:
https://github.com/dangbroitsdon/Wall-Jump-Unofficial-Fabric/blob/1.19-fabric/src/main/java/genandnic/walljump/client/SpeedBoostLogic.java#L31
fixes it. It looks basically the same as the forge version though (https://github.com/genandnic/Wall-Jump/blob/1.18.1/src/main/java/genandnic/walljump/client/SpeedBoostLogic.java#L27) except it uses a function instead of an assignment. Maybe there are some slight differences to how this works between forge and fabric, somehow? I remember also encountering this in the other unofficial fabric port (https://github.com/padlocks/Wall-Jump/blob/1.18-fabric/src/main/java/genandnic/walljump/mixin/client/ClientPlayerEntitySpeedBoostMixin.java#L47), so it may be something like that.

**Comment by dangbroitsdon** [comment]
thank you for contributing, my boy, i appreciate it on a whole nother level. changes shall be merged!

**Comment by artemisSystem** [comment]
Glad you like it. Please don't call me boy though, i'm not a boy 🥴. In general, i would advise against calling random strangers on the internet "my boy".

**Comment by dangbroitsdon** [comment]
my apologizes, i be calling everyone everything nowadays
